# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

cobblemon_version=1.5.0+1.20.1
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
fabric_loader_version=0.15.10

mappings_channel = parchment
mappings_version = 1.20.1:2023.09.03

# Mod Properties
mod_version = 1.2.0
maven_group = com.turtlehoarder.cobblemonchallenge
archives_base_name = cobblemonchallenge

# Dependencies
fabric_version=0.89.3+1.20.1
fabric_api_version=0.89.3+1.20.1

cloth_config_version=11.1.106



# Forge settings
forge_version=47.2.0
forge_version_range=[43,)
loader_version_range=[43,)

fabric.loom.multiProjectOptimisation=true