plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
    id 'org.jetbrains.kotlin.jvm' version "1.7.10"
}
architectury {
    platformSetupLoomIde()
    forge()
}

repositories {
    maven { url "https://thedarkcolour.github.io/KotlinForForge/"}
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

loom {
    silentMojangMappingsLicense()
}


configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

dependencies {
    forge "net.minecraftforge:forge:${forge_version}"
    minecraft("com.mojang:minecraft:${minecraft_version}");
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:${mappings_channel}-${mappings_version}@zip")
    }
    implementation("thedarkcolour:kotlinforforge:${kff_version}")

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive = false }
    modImplementation "com.cobblemon:forge:${cobblemon_version}"

}

def replaceProperties = [mod_id                 : "cobblemonchallenge",
                         mod_name               : "Cobblemon Challenge",
                         mod_description        : mod_description,
                         mod_version            : mod_version,
                         mod_authors            : mod_authors,
                         minecraft_version_range: minecraft_version_range,
                         forge_version_range    : forge_version_range,
                         loader_version_range   : loader_version_range]

processResources {
    inputs.properties replaceProperties
    filesMatching("META-INF/mods.toml") {
        expand replaceProperties
    }
}