plugins {
    id 'org.jetbrains.kotlin.jvm' version "1.7.10"
    id("dev.architectury.loom")
    id("architectury-plugin")
}

architectury  {
    platformSetupLoomIde()
    forge()
}

loom {
    runs {
        client {
            ideConfigGenerated(true)
        }
    }
    forge {
        dataGen {
            mod "cobblemonchallenge"
        }
    }
}


repositories {
    maven { url = 'https://maven.minecraftforge.net/' }
    mavenCentral()
}

configurations {
    common
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    forge("net.minecraftforge:forge:${rootProject.minecraft_version}-${rootProject.forge_version}")
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:${mappings_channel}-${mappings_version}@zip")
    }
    compileOnly "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    common(project(path: ":common", configuration: "namedElements")) { transitive false }
//	modImplementation "com.github.glitchfiend:TerraBlender-forge:${rootProject.minecraft_version}-${rootProject.terrablender_version}"
  //  common(project(path: ":common", configuration: "namedElements")) { transitive false }
 //   shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive false }
}

configurations {
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

repositories {
    maven { url = 'https://maven.minecraftforge.net/' }
    maven {
        url = "https://maven.impactdev.net/repository/development"
        content {
            includeGroup 'com.cobblemon'
        }
    }
    mavenCentral()
}

// Include resources generated by data generators.
sourceSets {
    main {
        resources {
            srcDirs "src/generated/resources"
            exclude ".cache"
        }
    }
}

sourcesJar {
    duplicatesStrategy "exclude"
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}