plugins {
    id "org.jetbrains.kotlin.jvm" version "1.9.23"
}

dependencies {
    // This gives an api version compatible with multiloader
    modApi "com.cobblemon:mod:$cobblemon_version"
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modImplementation "dev.architectury:architectury:$rootProject.architectury_version"
}

architectury {
    common("neoforge", "fabric")
}

